% Example_tri_tri_contour_plot_cir.m
% Nasser June 18, 2019
clear;clc
% The data in the files:
% xtritri5_pt.mat, ytritri5_pt.mat, Rtritri5_pt
% which has been generated by the MATLAB file:
% Example_tri_tri_contour_save_cir.m
% will be loaded in this file to plot Figure 11 (left)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
% 
%
%%
n        =   3*2^13
t        =  (0:2*pi/n:2*pi-2*pi/n).';
% The parametization of the rectangle boundary
out_ver    = [0    ; 5    ; 4+5i ]; % Vertices of the outer triangle
in_ver     = [3+3i ; 4+3i ; 3+i  ]; % Vertices of the iner triangle
[et(1:n,1)     , etp(1:n,1)     ] = polygonp(out_ver,n/length(out_ver));
[et(n+1:2*n,1) , etp(n+1:2*n,1) ] = polygonp(in_ver,n/length(in_ver));
%
x=load('xtritri5_pt.mat','-ascii');
y=load('ytritri5_pt.mat','-ascii');
R=load('Rtritri5_pt.mat','-ascii');
%
figure
tv=[0.13,0.55,0.72,1,1.12,1.21];
tvr=[0.3347,0.399,0.8467];
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
contour(x,y,R,tvr,'Color','r','LineWidth',1.0);
plot(real(et(1:n,1)),imag(et(1:n,1)),'k','LineWidth',1.2)
plot(real(et(n+1:2*n,1)),imag(et(n+1:2*n,1)),'k','LineWidth',1.2)
set(gca,'XTick',[0:1:5],'FontSize',18);
set(gca,'YTick',[0:1:5]);
% plot(x,y,'.r','markerFaceColor','r')
axis equal
axis([-0.01  5.01 -0.01  5.01])
axis off
set(gca,'LooseInset',get(gca,'TightInset'))
print -depsc fig_tritri5
% print -dpdf  fig_tritri5
%