% Example_Rec_Rec_line_plot.m
% Nasser June 12, 2019
clear;clc
% The data in the files:

% s_rr_h_0_pt.mat, Rs_rr_h_0_1_pt.mat, Rs_rr_h_0_2_pt.mat, 
% Rs_rr_h_0_3_pt.mat, 

% s_rr_v_0_pt.mat, Rs_rr_v_0_1_pt.mat, Rs_rr_v_0_2_pt.mat,
% Rs_rr_v_0_3_pt.mat, Rs_rr_v_0_4_pt.mat

% s_rr_v_5_pt.mat, Rs_rr_v_5_1_pt.mat, Rs_rr_v_5_2_pt.mat,
% Rs_rr_v_5_3_pt.mat, Rs_rr_v_5_4_pt.mat

% which has been generated by the MATLAB files:
% Example_Rec_Rec_line_save_h0.m
% Example_Rec_Rec_line_save_v0.m
% Example_Rec_Rec_line_save_v5.m
% will be loaded in this file to plot Figure 10
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
%
% loading the data files for the canonical domain: 
% the unit disk with a radial slit
% horizontal limit 

%%
x0h =load('s_rr_h_0_pt.mat','-ascii');
R0h1=load('Rs_rr_h_0_1_pt.mat','-ascii');
R0h2=load('Rs_rr_h_0_2_pt.mat','-ascii');
R0h3=load('Rs_rr_h_0_3_pt.mat','-ascii');

figure
hold on
box on
plot(x0h,R0h1,'-r','LineWidth',1.5)
plot(x0h,R0h2,':b','LineWidth',1.5)
plot(x0h,R0h3,'--k','LineWidth',1.5)

legend({'$R(G,x)$','$R(G,x+0.25{\rm i})$','$R(G,x+0.5{\rm i})$'},'FontSize',15,'Interpreter','latex','Location','northwest');

xlabel('{$x$}','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[-3:1:3],'FontSize',18);
set(gca,'YTick',[0:5:20]);

grid(gca,'minor')
ax=gca;
ax.MinorGridAlpha = 1;

axis([-3 3 0 20])
set(gca,'LooseInset',get(gca,'TightInset'))

% axis equal
% axis off
% print -depsc fig_0hrecrecL
% print -dpdf  fig_0hrecrecL
%%
x0v =load('s_rr_v_0_pt.mat','-ascii');
R0v1=load('Rs_rr_v_0_1_pt.mat','-ascii');
R0v2=load('Rs_rr_v_0_2_pt.mat','-ascii');
R0v3=load('Rs_rr_v_0_3_pt.mat','-ascii');
R0v4=load('Rs_rr_v_0_4_pt.mat','-ascii');

figure
hold on
box on
plot(x0v,R0v1,'-r','LineWidth',1.5)
plot(x0v,R0v2,'-.m','LineWidth',1.5)
plot(x0v,R0v3,':b','LineWidth',1.5)
plot(x0v,R0v4,'--k','LineWidth',1.5)

legend({'$R(G,{\rm i}\, y)$','$R(G,0.25+{\rm i}\, y)$','$R(G,0.5+{\rm i}\, y)$','$R(G,1+{\rm i}\, y)$'},'FontSize',15,'Interpreter','latex','Location','northwest');

xlabel('{$y$}','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[-1:0.5:1],'FontSize',18);
set(gca,'YTick',[0:5:20]);

grid(gca,'minor')
ax=gca;
ax.MinorGridAlpha = 1;

axis([-1 1 0 20])
set(gca,'LooseInset',get(gca,'TightInset'))

% axis equal
% axis off
% print -depsc fig_0vrecrecL
% print -dpdf  fig_0vrecrecL
%%
x5v =load('s_rr_v_5_pt.mat','-ascii');
R5v1=load('Rs_rr_v_5_1_pt.mat','-ascii');
R5v2=load('Rs_rr_v_5_2_pt.mat','-ascii');
R5v3=load('Rs_rr_v_5_3_pt.mat','-ascii');
R5v4=load('Rs_rr_v_5_4_pt.mat','-ascii');

figure
hold on
box on
plot(x5v , R5v1,'-r','LineWidth',1.5)
plot(x5v , R5v2,'-.m','LineWidth',1.5)
plot(x5v , R5v3,':b','LineWidth',1.5)
plot(x5v , R5v4,'--k','LineWidth',1.5)

hh=legend({'$R(G,{\rm i}\, y)$','$R(G,0.25+{\rm i}\, y)$','$R(G,0.5+{\rm i}\, y)$','$R(G,1+{\rm i}\, y)$'},'FontSize',15,'Interpreter','latex','Location','northeast');
% pos = get(hh,'Position');
% posx =  0.58;
% posy =  0.2;
% set(hh,'Position',[posx posy pos(3) pos(4)]);

xlabel('{$y$}','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[-1:0.5:1],'FontSize',18);
set(gca,'YTick',[0:0.2:1.0]);

grid(gca,'minor')
ax=gca;
ax.MinorGridAlpha = 1;

axis([-1 1 0 1.0])
set(gca,'LooseInset',get(gca,'TightInset'))

% axis equal
% axis off
% print -depsc fig_5vrecrecL
% print -dpdf  fig_5vrecrecL
%