% Example_6cr502_contour_plot.m
% Nasser June 22, 2019
clear;clc
% The data in the files:
% x5cr_502_pt.mat, y5cr_502_pt.mat, R5cr_502_pt.mat
% which has been generated by the MATLAB file:
% Example_6cr502_contour_save_cir.m
% will be loaded in this file to plot Figure 16 (second row, right)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
% 
%
%%
n  =  2^14;
t  = [0:2*pi/n:2*pi-2*pi/n].';
k  =  1; % the unit circle: |z|=1
et(1+(k-1)*n:k*n,1)  =  1.* exp(i.*t);
etp(1+(k-1)*n:k*n,1) =  1i.*exp(i.*t);
k  =  2; % the inner circle: |z-0.0|=0.2
et(1+(k-1)*n:k*n,1)  =  0.0 +0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
k  =  3; % the inner circle: |z-0.6|=0.2
et(1+(k-1)*n:k*n,1)  =  0.6 +0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
k  =  4; % the inner circle: |z-0.6i|=0.2
et(1+(k-1)*n:k*n,1)  =  0.6i+0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
k  =  5; % the inner circle: |z+0.6|=0.2
et(1+(k-1)*n:k*n,1)  = -0.6 +0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
k  =  6; % the inner circle: |z+0.6i|=0.2
et(1+(k-1)*n:k*n,1)  = -0.6i+0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
%
x=load('x5cr_502_pt.mat','-ascii');
y=load('y5cr_502_pt.mat','-ascii');
R=load('R5cr_502_pt.mat','-ascii');
%%
R(abs(x+i*y-0.6i)<0.209)=NaN;
R(abs(x+i*y+0.6i)<0.209)=NaN;
tv=[0.08,0.3,0.45,0.6,0.85,1.5,2.5,7];
tvr=[0.178,3.67,4.48];
figure
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
contour(x,y,R,tvr,'Color','r','LineWidth',1.0);
for k=1:6
    crv = et(1+(k-1)*n:k*n,1);crv(end+1)=crv(1);
    plot(real(crv),imag(crv),'k','LineWidth',1.5)
end

set(gca,'XTick',[-1:1:1],'FontSize',15);
set(gca,'YTick',[-1:1:1]);

set(gca,'LooseInset',get(gca,'TightInset'))
axis equal
axis off
% print -depsc fig_5cir50
% print -dpdf  fig_5cir50
set(gcf,'renderer','painters')
print(gcf,'-depsc2','fig_5cir502.eps')
print(gcf,'-dpdf','fig_5cir502.pdf')
%