% Example_Rec_slit_contour_plot_cir.m
% Nasser June 12, 2019
clear;clc
% The data in the files:
% xrecslit5_pt.mat, yrecslit5_pt.mat, Rrecslit5_pt
% which has been generated by the MATLAB file:
% Example_Rec_slit_contour_save_cir.m
% will be loaded in this file to plot Figure 9 (left)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
% 
%%
n        =   2^15
t        =  (0:2*pi/n:2*pi-2*pi/n).';
% The parametization of the rectangle boundary
rec_ver    = [3+i   ; -3+i   ; -3-i    ;   3-i  ]; % Vertices of the rectangle
[zet(1:n,1)    ,zetp(1:n,1)    ] = polygonp(rec_ver,n/length(rec_ver));
%
%
x=load('xrecslit5_pt.mat','-ascii');
y=load('yrecslit5_pt.mat','-ascii');
R=load('Rrecslit5_pt.mat','-ascii');
%
figure
tv=[0.1,0.25,0.5,0.8,1,1.05,1.13,1.175,1.23,1.25];
tvr=[0.9549,0.95665];
% tvr=[0.957,0.957];
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
contour(x,y,R,tvr,'Color','r','LineWidth',1.0);
plot(real(zet(1:n,1)),imag(zet(1:n,1)),'k','LineWidth',1.2)
plot([0 1],[0 0],'k','LineWidth',1.2)
axis equal
axis([-3.01  3.01 -1.01  1.01])
axis off
set(gca,'LooseInset',get(gca,'TightInset'))
% print -depsc fig_rec5
% print -dpdf  fig_rec5
%
%
% R1=R;
% R1(R1>=2.1)=NaN;
% figure
% surf(x,y,R1);
% hold on
% shading interp
% colormap jet
% view(140,20)
%  
% contour(x,y,R,tv,'Color','k','LineWidth',1.0);
% % box on
% for k=1:2
%     crv = et(1+(k-1)*n:k*n,1);crv(end+1)=crv(1);
%     plot(real(crv),imag(crv),'k','LineWidth',1.5)
% end
% % set(gca,'XTick',[-3:1:3],'FontSize',15);
% % set(gca,'YTick',[-3:1:3]);
% % set(gca,'LooseInset',get(gca,'TightInset'))
% axis equal
% axis([-3 3 -3 3 0 1.5])
%