% Example_ann_line_plot_cir.m
% Nasser June 12, 2019
clear;clc
% The data in the files:
% san0_pt.mat, Rsan0_pt.mat, san5_pt.mat, Rsan5_pt.mat,
% which has been generated by the MATLAB files:
% Example_ann_line_save_cir.m
% Example_ann_line_save_rad.m
% will be loaded in this file to plot Figure 4 in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
%
% loading the data files for the canonical domain: 
% the unit disk with a radial slit
x0 =load('san0_pt.mat','-ascii');
R0=load('Rsan0_pt.mat','-ascii');
% loading the data files for the canonical domain: 
% the unit disk with a circular slit
x5 =load('san5_pt.mat','-ascii');
R5=load('Rsan5_pt.mat','-ascii');
%
%
% Plot the figure
figure
hold on
box on
plot(x0,R0,'b','LineWidth',1.5)
plot(x5,R5,'r','LineWidth',1.5)
legend({'$\theta_1=0$','$\theta_1=\pi/2$'},'FontSize',15,'Interpreter','latex','Location','northeast');
xlabel('{$x$}','FontSize',18,'Interpreter','latex');
ylabel('$R(G,x)$','FontSize',18,'Interpreter','latex');
set(gca,'XTick',[-1:0.25:1],'FontSize',18);
set(gca,'YTick',[0:2:10]);
grid(gca,'minor')
ax=gca;
ax.MinorGridAlpha = 1;
axis([-1 1 0 10])
set(gca,'LooseInset',get(gca,'TightInset'))
% axis equal
% axis off
% print -depsc fig_an_allL
% print -dpdf  fig_an_allL
%
% 
% 
% figure
% hold on
% box on
% plot(x0,R0,'b','LineWidth',1.5)
% plot(x5,R5,'r','LineWidth',1.5)
% 
% legend({'$\theta_1=0$','$\theta_1=\pi/2$'},'FontSize',15,'Interpreter','latex','Location','north');
% 
% xlabel('{$x$}','FontSize',18,'Interpreter','latex');
% ylabel('$R(x)$','FontSize',18,'Interpreter','latex');
% 
% set(gca,'XTick',[-1:0.5:1],'FontSize',18);
% set(gca,'YTick',[0:0.1:0.5]);
% 
% grid(gca,'minor')
% ax=gca;
% ax.MinorGridAlpha = 1;
% 
% axis([-1 1 0 0.7])
% set(gca,'LooseInset',get(gca,'TightInset'))
% % axis equal
% % axis off
%