% Example_Rec_slit_contour_plot_rad.m
% Nasser June 12, 2019
clear;clc
% The data in the files:
% xrecslit0_pt.mat, yrecslit0_pt.mat, Rrecslit0_pt
% which has been generated by the MATLAB file:
% Example_Rec_slit_contour_save_rad.m
% will be loaded in this file to plot Figure 9 (right)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
% 
%%
n        =   2^15
t        =  (0:2*pi/n:2*pi-2*pi/n).';
% The parametization of the rectangle boundary
rec_ver    = [3+i   ; -3+i   ; -3-i    ;   3-i  ]; % Vertices of the rectangle
[zet(1:n,1)    ,zetp(1:n,1)    ] = polygonp(rec_ver,n/length(rec_ver));
%
%
x=load('xrecslit0_pt.mat','-ascii');
y=load('yrecslit0_pt.mat','-ascii');
R=load('Rrecslit0_pt.mat','-ascii');
%
figure
tv=[0.1,0.35,0.6,0.9,1.1,1.2,1.25,1.275,1.4,2,4];
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
plot(real(zet(1:n,1)),imag(zet(1:n,1)),'k','LineWidth',1.2)
plot([0 1],[0 0],'k','LineWidth',1.2)
axis equal
axis([-3.01  3.01 -1.01  1.01])
axis off
set(gca,'LooseInset',get(gca,'TightInset'))
% print -depsc fig_rec0
% print -dpdf  fig_rec0
%
%
% R1=R;
% R1(R1>=2.0)=NaN;
% figure
% surf(x,y,R1);
% hold on
% shading interp
% colormap jet
% view(140,20)
%  
% contour(x,y,R,tv,'Color','k','LineWidth',1.0);
% % box on
% plot(real(zet(1:n,1)),imag(zet(1:n,1)),'k','LineWidth',1.2)
% plot([0 1],[0 0],'k','LineWidth',1.2)
% % set(gca,'XTick',[-3:1:3],'FontSize',15);
% % set(gca,'YTick',[-3:1:3]);
% % set(gca,'LooseInset',get(gca,'TightInset'))
% axis equal
% axis([-3 3 -3 3 0 2.0])
%