% Example_squ_cir_contour_plot_cir.m
% Nasser June 22, 2019
clear;clc
% The data in the files:
% xsqucir5_pt.mat, ysqucir5_pt.mat, Rsqucir5_pt
% which has been generated by the MATLAB file:
% Example_squ_cir_contour_save_cir.m
% will be loaded in this file to plot Figure 13 (second row, left)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
% 
%
%%
n        =   2^15
t        =  (0:2*pi/n:2*pi-2*pi/n).';
% The parametization of the rectangle boundary
et(1:n,1)   =     exp(i.*t);
etp(1:n,1)  =  i.*exp(i.*t);
irec_ver    = [0.25+0.25i ;  0.25-0.25i  ; -0.25-0.25i ; -0.25+0.25i ]; % Vertices of the iner square
[et(n+1:2*n,1) , etp(n+1:2*n,1) ] = polygonp(irec_ver,n/length(irec_ver));
%
x=load('xsqucir5_pt.mat','-ascii');
y=load('ysqucir5_pt.mat','-ascii');
R=load('Rsqucir5_pt.mat','-ascii');
%%
figure
tv=[0.1,0.28,0.45,0.57,0.595];
tvr=[0.548451,0.548451];
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
contour(x,y,R,tvr,'Color','r','LineWidth',1.0);
plot(real(et(1:n,1)),imag(et(1:n,1)),'k','LineWidth',1.2)
plot(real(et(n+1:2*n,1)),imag(et(n+1:2*n,1)),'k','LineWidth',1.2)
axis equal
grid on
axis([-1.01  1.01 -1.01  1.01])
axis off
set(gca,'LooseInset',get(gca,'TightInset'))
print -depsc fig_squcir5
print -dpdf  fig_squcir5
%