% Example_3cr_line_plot_00.m
% Nasser June 12, 2019
clear;clc
% The data in the files:
% s3cr_00_pt.mat, Rs3cr_00_pt.mat,
% which has been generated by the MATLAB file:
% Example_3cr_line_save_00.m
% will be loaded in this file to plot Figure 15 (center)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
%
% loading the data files 
x=load('s3cr_00_pt.mat','-ascii');
R=load('Rs3cr_00_pt.mat','-ascii');
%
%
% Plot the figure
figure
hold on
box on
plot(x,R,'b','LineWidth',1.5)
xlabel('{$x$}','FontSize',18,'Interpreter','latex');
ylabel('$R(G,x)$','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[-3:1:3],'FontSize',18);
set(gca,'YTick',[0:10:50]);

grid(gca,'minor')
ax=gca;
ax.MinorGridAlpha = 1;

axis([-3 3 0 50])
set(gca,'LooseInset',get(gca,'TightInset'))
% axis equal
% axis off
% print -depsc fig_cir3_2L
% print -dpdf  fig_cir3_2L
%