% Example_squ_cir_contour_plot_rad.m
% Nasser June 22, 2019
clear;clc
% The data in the files:
% xsqucir0_pt.mat, ysqucir0_pt.mat, Rsqucir0_pt
% which has been generated by the MATLAB file:
% Example_squ_cir_contour_save_rad.m
% will be loaded in this file to plot Figure 13 (second row, right)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
% 
%
%%
n        =   2^15
t        =  (0:2*pi/n:2*pi-2*pi/n).';
% The parametization of the rectangle boundary
et(1:n,1)   =     exp(i.*t);
etp(1:n,1)  =  i.*exp(i.*t);
irec_ver    = [0.25+0.25i ;  0.25-0.25i  ; -0.25-0.25i ; -0.25+0.25i ]; % Vertices of the iner square
[et(n+1:2*n,1) , etp(n+1:2*n,1) ] = polygonp(irec_ver,n/length(irec_ver));
%
x=load('xsqucir0_pt.mat','-ascii');
y=load('ysqucir0_pt.mat','-ascii');
R=load('Rsqucir0_pt.mat','-ascii');
%%
figure
tv=[0.1,0.25,0.4,0.55,0.7,0.9,1.1,1.5,2.2,4,6,10];
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
plot(real(et(1:n,1)),imag(et(1:n,1)),'k','LineWidth',1.2)
plot(real(et(n+1:2*n,1)),imag(et(n+1:2*n,1)),'k','LineWidth',1.2)
axis equal
grid on
axis([-1.01  1.01 -1.01  1.01])
axis off
set(gca,'LooseInset',get(gca,'TightInset'))
print -depsc fig_squcir0
print -dpdf  fig_squcir0
%