% Example_Rec_Rec_contour_plot_cir.m
% Nasser June 12, 2019
clear;clc
% The data in the files:
% xrecrec5_pt.mat, yrecrec5_pt.mat, Rrecrec5_pt
% which has been generated by the MATLAB file:
% Example_Rec_Rec_contour_save_cir.m
% will be loaded in this file to plot Figure 11 (left)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
% 
%
%%
n        =   2^15
t        =  (0:2*pi/n:2*pi-2*pi/n).';
% The parametization of the rectangle boundary
orec_ver    = [3+i    ; -3+i   ; -3-i    ;   3-i  ]; % Vertices of the outer rectangle
irec_ver    = [1+0.5i ;  1     ;  0      ;   0.5i  ]; % Vertices of the iner rectangle
[et(1:n,1)     , etp(1:n,1)     ] = polygonp(orec_ver,n/length(orec_ver));
[et(n+1:2*n,1) , etp(n+1:2*n,1) ] = polygonp(irec_ver,n/length(irec_ver));
%
x=load('xrecrec5_pt.mat','-ascii');
y=load('yrecrec5_pt.mat','-ascii');
R=load('Rrecrec5_pt.mat','-ascii');
%
figure
tv=[0.12,0.27,0.433,0.65,0.834,0.95,1.05,1.14,1.2,1.238];
tvr=[0.4259,0.83027];
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
contour(x,y,R,tvr,'Color','r','LineWidth',1.0);
plot(real(et(1:n,1)),imag(et(1:n,1)),'k','LineWidth',1.2)
plot(real(et(n+1:2*n,1)),imag(et(n+1:2*n,1)),'k','LineWidth',1.2)
axis equal
axis([-3.01  3.01 -1.01  1.01])
axis off
set(gca,'LooseInset',get(gca,'TightInset'))
% print -depsc fig_recrec5
% print -dpdf  fig_recrec5
%