% Example_Rec_slit_line_plot.m
% Nasser June 12, 2019
clear;clc
% The data in the files:

% s_rs_h_0_pt.mat, Rs_rs_h_0_pt.mat, 

% s_rs_v_0_pt.mat, Rs_rs_v_0_1_pt.mat, Rs_rs_v_0_2_pt.mat,
% Rs_rs_v_0_3_pt.mat, Rs_rs_v_0_4_pt.mat

% s_rs_v_5_pt.mat, Rs_rs_v_5_1_pt.mat, Rs_rs_v_5_2_pt.mat,
% Rs_rs_v_5_3_pt.mat, Rs_rs_v_5_4_pt.mat

% which has been generated by the MATLAB files:
% Example_Rec_slit_line_save_h0.m
% Example_Rec_slit_line_save_v0.m
% Example_Rec_slit_line_save_v5.m
% will be loaded in this file to plot Figure 10
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
%
% loading the data files for the canonical domain: 
% the unit disk with a radial slit
% horizontal limit 
x0 =load('s_rs_h_0_pt.mat','-ascii');
R01=load('Rs_rs_h_0_pt.mat','-ascii');

figure
hold on
box on
plot(x0,R01,'-r','LineWidth',1.5)

legend({'$R(G,x)$'},'FontSize',15,'Interpreter','latex','Location','northeast');

xlabel('{$x$}','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[-3:1:3],'FontSize',18);
set(gca,'YTick',[0:.5:2]);

grid(gca,'minor')
ax=gca;
ax.MinorGridAlpha = 1;

axis([-3 3 0 2])
set(gca,'LooseInset',get(gca,'TightInset'))
% axis equal
% axis off
% print -depsc fig_0hrecL
% print -dpdf  fig_0hrecL
%
% 
% 
% loading the data files for the canonical domain: 
% the unit disk with a radial slit
% vertical limit 
x0v =load('s_rs_v_0_pt.mat','-ascii');
R0v1=load('Rs_rs_v_0_1_pt.mat','-ascii');
R0v2=load('Rs_rs_v_0_2_pt.mat','-ascii');
R0v3=load('Rs_rs_v_0_3_pt.mat','-ascii');
R0v4=load('Rs_rs_v_0_4_pt.mat','-ascii');

x0vn=[x0v(1:252) 0 x0v(253:end)];
R0vn1=[R0v1(1:252) NaN R0v1(253:end)];
R0vn4=[R0v4(1:252) NaN R0v4(253:end)];

figure
hold on
box on
plot(x0vn,R0vn1,'-r','LineWidth',1.5)
plot(x0v,R0v2,'-.m','LineWidth',1.5)
plot(x0v,R0v3,':b','LineWidth',1.5)
plot(x0vn,R0vn4,'--k','LineWidth',1.5)

legend({'$R(G,{\rm i}\, y)$','$R(G,0.25+{\rm i}\, y)$','$R(G,0.5+{\rm i}\, y)$','$R(G,1+{\rm i}\, y)$'},'FontSize',15,'Interpreter','latex','Location','northeast');

xlabel('{$y$}','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[-1:0.5:1],'FontSize',18);
set(gca,'YTick',[0:2:10]);

grid(gca,'minor')
ax=gca;
ax.MinorGridAlpha = 1;

axis([-1 1 0 10])
set(gca,'LooseInset',get(gca,'TightInset'))

% axis equal
% axis off
% print -depsc fig_0vrecL
% print -dpdf  fig_0vrecL
%
%
%
% loading the data files for the canonical domain: 
% the unit disk with a circular slit
% vertical limit 
x5v =load('s_rs_v_5_pt.mat','-ascii');
R5v1=load('Rs_rs_v_5_1_pt.mat','-ascii');
R5v2=load('Rs_rs_v_5_2_pt.mat','-ascii');
R5v3=load('Rs_rs_v_5_3_pt.mat','-ascii');
R5v4=load('Rs_rs_v_5_4_pt.mat','-ascii');

x5vn =[x5v(1:252)  0   x5v(253:end)];
R5vn1=[R5v1(1:252) NaN R5v1(253:end)];
R5vn2=[R5v2(1:252) NaN R5v2(253:end)];
R5vn3=[R5v3(1:252) NaN R5v3(253:end)];
R5vn4=[R5v4(1:252) NaN R5v4(253:end)];

figure
hold on
box on
plot(x5vn , R5vn1,'-r','LineWidth',1.5)
plot(x5vn , R5vn2,'-.m','LineWidth',1.5)
plot(x5vn , R5vn3,':b','LineWidth',1.5)
plot(x5vn , R5vn4,'--k','LineWidth',1.5)

hh=legend({'$R(G,{\rm i}\, y)$','$R(G,0.25+{\rm i}\, y)$','$R(G,0.5+{\rm i}\, y)$','$R(G,1+{\rm i}\, y)$'},'FontSize',15,'Interpreter','latex','Location','northeast');
pos = get(hh,'Position');
posx =  0.56;
posy =  0.18;
set(hh,'Position',[posx posy pos(3) pos(4)]);

xlabel('{$y$}','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[-1:0.5:1],'FontSize',18);
set(gca,'YTick',[0:0.2:1.2]);

grid(gca,'minor')
ax=gca;
ax.MinorGridAlpha = 1;

axis([-1 1 0 1.2])
set(gca,'LooseInset',get(gca,'TightInset'))

% axis equal
% axis off
% print -depsc fig_5vrecL
% print -dpdf  fig_5vrecL
%