% Example_2cr5_line_plot_cir.m
% Nasser June 12, 2019
clear;clc
% The data in the files:
% s2cr05_0_pt.mat, Rs2cr05_0_pt.mat, s2cr05_5_pt.mat, Rs2cr05_5_pt.mat,
% which has been generated by the MATLAB files:
% Example_2cr05_line_save_cir.m
% Example_2cr05_line_save_rad.m
% will be loaded in this file to plot Figure 5 (first row, right)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
%
% loading the data files for the canonical domain: 
% the unit disk with a radial slit
x0=load('s2cr05_0_pt.mat','-ascii');
R0=load('Rs2cr05_0_pt.mat','-ascii');
% loading the data files for the canonical domain: 
% the unit disk with a circular slit
x5=load('s2cr05_5_pt.mat','-ascii');
R5=load('Rs2cr05_5_pt.mat','-ascii');
%
%
% Plot the figure
figure
hold on
box on
plot(x0,R0,'b','LineWidth',1.5)
plot(x5,R5,'r','LineWidth',1.5)

legend({'$\theta_1=0$','$\theta_1=\pi/2$'},'FontSize',15,'Interpreter','latex','Location','northeast');

xlabel('{$x$}','FontSize',18,'Interpreter','latex');
ylabel('$R(G,x)$','FontSize',18,'Interpreter','latex');

set(gca,'XTick',[-1:0.25:1],'FontSize',18);
set(gca,'YTick',[0:2:10]);

grid(gca,'minor')
ax=gca;
ax.MinorGridAlpha = 1;

axis([-1 1 0 10])
set(gca,'LooseInset',get(gca,'TightInset'))
% axis equal
% axis off
% print -depsc fig_2cr3_allL
% print -dpdf  fig_2cr3_allL
%