% Example_6cr55_contour_plot.m
% Nasser June 22, 2019
clear;clc
% The data in the files:
% x5cr_55_pt.mat, y5cr_55_pt.mat, R5cr_55_pt.mat,
% which has been generated by the MATLAB file:
% Example_6cr55_contour_save.m
% will be loaded in this file to plot Figure 16 (first row, left)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
% 
%
%%
n  =  2^14;
t  = [0:2*pi/n:2*pi-2*pi/n].';
k  =  1; % the unit circle: |z|=1
et(1+(k-1)*n:k*n,1)  =  1.* exp(i.*t);
etp(1+(k-1)*n:k*n,1) =  1i.*exp(i.*t);
k  =  2; % the inner circle: |z-0.0|=0.2
et(1+(k-1)*n:k*n,1)  =  0.0 +0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
k  =  3; % the inner circle: |z-0.6|=0.2
et(1+(k-1)*n:k*n,1)  =  0.6 +0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
k  =  4; % the inner circle: |z-0.6i|=0.2
et(1+(k-1)*n:k*n,1)  =  0.6i+0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
k  =  5; % the inner circle: |z+0.6|=0.2
et(1+(k-1)*n:k*n,1)  = -0.6 +0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
k  =  6; % the inner circle: |z+0.6i|=0.2
et(1+(k-1)*n:k*n,1)  = -0.6i+0.2.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =      -0.2i.*exp(-i.*t);
%
x=load('x5cr_55_pt.mat','-ascii');
y=load('y5cr_55_pt.mat','-ascii');
R=load('R5cr_55_pt.mat','-ascii');
%%
tv=[0.1,0.23,0.33,0.37,0.42,0.45];
tvr=[0.1693,0.2736];
figure
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
contour(x,y,R,tvr,'Color','r','LineWidth',1.0);
for k=1:6
    crv = et(1+(k-1)*n:k*n,1);crv(end+1)=crv(1);
    plot(real(crv),imag(crv),'k','LineWidth',1.5)
end

set(gca,'XTick',[-1:1:1],'FontSize',15);
set(gca,'YTick',[-1:1:1]);

set(gca,'LooseInset',get(gca,'TightInset'))
axis equal
axis off
% print -depsc fig_5cir55
% print -dpdf  fig_5cir55
% print('fig_5cir55','-depsc','-r1000')
set(gcf,'renderer','painters')
print(gcf,'-depsc2','fig_5cir55.eps')
%