% Example_2cr05_contour_plot_cir.m
% Nasser June 12, 2019
clear;clc
% The data in the files:
% x2cr05_5_pt.mat, y2cr05_5_pt.mat, R2cr05_5_pt.mat,
% which has been generated by the MATLAB file:
% Example_2cr05_contour_save_cir.m
% to plot the contour lines in Figure 5 (first row, left) in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
%
% The parametrization of the boundary
n  =  2^14;
t  = [0:2*pi/n:2*pi-2*pi/n].';
k  =  1; % the unit circle: |z|=1
et(1+(k-1)*n:k*n,1)  =  1.* exp(i.*t);
k  =  2; % the inner circle: |z-0.05|=0.25
et(1+(k-1)*n:k*n,1)  =  0.05+0.25.* exp(-i.*t);
% loading the data files
x=load('x2cr05_5_pt.mat','-ascii');
y=load('y2cr05_5_pt.mat','-ascii');
R=load('R2cr05_5_pt.mat','-ascii');
% plot the contour lines
tv  = [0.136,0.28,0.41,0.53,0.58976,0.61,0.63,0.65]; %level values
tvr  = [0.58976,0.58976]; %level values
figure
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
contour(x,y,R,tvr,'Color','r','LineWidth',1.0);
for k=1:2
    crv = et(1+(k-1)*n:k*n,1);crv(end+1)=crv(1);
    plot(real(crv),imag(crv),'k','LineWidth',1.5)
end

set(gca,'XTick',[-3:1:3],'FontSize',15);
set(gca,'YTick',[-3:1:3]);
axis equal
axis([-1.01 1.01 -1.01 1.01])
set(gca,'LooseInset',get(gca,'TightInset'))
% axis off
% print -depsc fig_2cr_5R3
% print -dpdf  fig_2cr_5R3
%
%
% 
% R1=R;
% R1(R1>=1.1)=NaN;
% figure
% surf(x,y,R1);
% hold on
% shading interp
% colormap jet
% view(115,25)
%  
% % box on
% for k=1:2
%     crv = et(1+(k-1)*n:k*n,1);crv(end+1)=crv(1);
%     plot(real(crv),imag(crv),'k','LineWidth',1.5)
% end
% % set(gca,'XTick',[-3:1:3],'FontSize',15);
% % set(gca,'YTick',[-3:1:3]);
% % set(gca,'LooseInset',get(gca,'TightInset'))
% % axis equal
% axis([-1 1 -1 1 0 1])
%