% Example_3cr00_contour_plot.m
% Nasser June 22, 2019
clear;clc
% The data in the files:
% x3cr_00_pt.mat, y3cr_00_pt.mat, R3cr_00_pt.mat,
% which has been generated by the MATLAB file:
% Example_3cr00_contour_save.m
% will be loaded in this file to plot Figure 14 (center)
% in the paper:
% E. Kalmoun, M. Nasser and M. Vuorinen, Numerical computation of Mityuk's
% function and radius for some canonical slit domains. 
% 
% 
%
%%
n  =  2^14;
t  = [0:2*pi/n:2*pi-2*pi/n].';
n  =  2^14;
t  = [0:2*pi/n:2*pi-2*pi/n].';
k  =  1;
et(1+(k-1)*n:k*n,1)  =  3.* exp(i.*t);
etp(1+(k-1)*n:k*n,1) =  3i.*exp(i.*t);
k  =  2;
et(1+(k-1)*n:k*n,1)  =  1.5+1.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =     -1i.*exp(-i.*t);
k  =  3;
et(1+(k-1)*n:k*n,1)  = -1.5+1.* exp(-i.*t);
etp(1+(k-1)*n:k*n,1) =     -1i.*exp(-i.*t);
%
x=load('x3cr_00_pt.mat','-ascii');
y=load('y3cr_00_pt.mat','-ascii');
R=load('R3cr_00_pt.mat','-ascii');
%%
tv  = [0.15,0.35,0.6,0.9,1.3,2,3,4.5,7,16]; %level values
tvr = [11.036 11.036]; %level values
figure
hold on
box on
contour(x,y,R,tv,'Color','b','LineWidth',1.0);
contour(x,y,R,tvr,'Color','r','LineWidth',1.0);
for k=1:3
    crv = et(1+(k-1)*n:k*n,1);crv(end+1)=crv(1);
    plot(real(crv),imag(crv),'k','LineWidth',1.5)
end

set(gca,'XTick',[-3:1:3],'FontSize',15);
set(gca,'YTick',[-3:1:3]);

set(gca,'LooseInset',get(gca,'TightInset'))
axis equal
% axis off
% print -depsc fig_5cir00
% print -dpdf  fig_5cir00
set(gcf,'renderer','painters')
print(gcf,'-depsc2','fig_3cir00.eps')
%